### ISSUE TITLE
Как воспользоваться секретом? 

### ISSUE THREAD

**Issue by romanm-azazaz** [yc-actions/yc-lockbox#447]
В документации я не нашёл никаких outputs а ${{ steps.lockbox-secret.outputs.stdout }} пуст. Подскажите, пожалуйста, как его использовать? Мне показалось, что это работает примерно как hashicorp/vault-action.

**Comment by nikolaymatrosov** [comment]
А откуда вы взяли этот пример? Почему `stdout`?

**Comment by romanm-azazaz** [comment]
Мне это показалось логичным)

**Comment by nikolaymatrosov** [comment]
Вот здесь в коде задаются output'ы. https://github.com/yc-actions/yc-lockbox/blob/main/src/main.ts#L35-L36
Надеюсь, там все очевидно.

**Comment by romanm-azazaz** [comment]
Извините, я не разбираюсь в Js. Но из вашего ответа, я понял что сделать нужно так:
`    - name: Fetch secret kubeconf
      id: lockbox-secret
      uses: yc-actions/yc-lockbox@v1
      with:
        yc-sa-json-credentials: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        secret-id: ${{ secrets.SECRET_ID }}

    - name: Echo secret
      id: test
      env:
        VALUE: ${{ steps.lockbox-secret.outputs.value }}
        KEY: ${{ steps.lockbox-secret.outputs.key }}
      run:
       echo ${{ env.VALUE }} && echo ${{ env.KEY }}`
       
 Результат:
<img width="397" alt="image" src="https://github.com/yc-actions/yc-lockbox/assets/57663222/a4398077-c654-49f7-9b17-4bb5cd2029a1">

**Comment by nikolaymatrosov** [comment]
Нет. Ключ `key` соответствует ключу в [секрете](https://cloud.yandex.ru/docs/lockbox/concepts/secret#secret). По нему будет положено значение.
